documentation:
  - changed-files:
    - any-glob-to-any-file: ['**/*.md', 'docs/**/*']

tests:
  - changed-files:
    - any-glob-to-any-file: ['**/*.test.ts', '**/*.test.tsx', '**/*.spec.ts', '**/*.spec.tsx']

dependencies:
  - changed-files:
    - any-glob-to-any-file: ['package.json', 'pnpm-lock.yaml']

config:
  - changed-files:
    - any-glob-to-any-file: ['*.config.*', '.env*', 'tsconfig.json']

components:
  - changed-files:
    - any-glob-to-any-file: ['src/components/**/*']

api:
  - changed-files:
    - any-glob-to-any-file: ['src/app/api/**/*']

lib:
  - changed-files:
    - any-glob-to-any-file: ['src/lib/**/*']

styles:
  - changed-files:
    - any-glob-to-any-file: ['**/*.css', 'tailwind.config.*']

ci:
  - changed-files:
    - any-glob-to-any-file: ['.github/**/*']

i18n:
  - changed-files:
    - any-glob-to-any-file: ['src/i18n/**/*', 'src/proxy.ts']
